import { SQLDatabase } from "encore.dev/storage/sqldb";
import { PrismaClient } from "./prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";

// Define a database named 'encore_prisma_test', using the database migrations
// in the "./prisma/migrations" folder (where prisma will generate their migrations).
// Set `source` to `prisma` to let Encore know that the migrations are generated by Prisma.
const DB = new SQLDatabase("encore_prisma_test", {
  migrations: {
    path: "./prisma/migrations",
    source: "prisma",
  },
});

const prisma = new PrismaClient({
  adapter: new PrismaPg({ connectionString: DB.connectionString }),
});

export { prisma };
