package chat

import (
	"encore.app/chat/provider"
	llmprovider "encore.app/llm/provider"
	"encore.dev/pubsub"
)

// provider-message-sub is a subscription to the provider message topic. It handles
// all incoming messages from the providers.
//
// This uses Encore's pubsub package, learn more: https://encore.dev/docs/primitives/pubsub
var _ = pubsub.NewSubscription(
	provider.InboxTopic, "provider-message-sub",
	pubsub.SubscriptionConfig[*provider.Message]{
		Handler: pubsub.MethodHandler((*Service).ProcessProviderEvent),
	},
)

// llm-messages-sub is a subscription to the llm message topic. It handles
// messages generated by the llm providers
//
// This uses Encore's pubsub package, learn more: https://encore.dev/docs/primitives/pubsub
var _ = pubsub.NewSubscription(
	llmprovider.LLMMessageTopic, "llm-message-sub",
	pubsub.SubscriptionConfig[*llmprovider.BotResponse]{
		Handler: pubsub.MethodHandler((*Service).ProcessLLMMessage),
	},
)
