// Code generated by encore. DO NOT EDIT.

package auth

import "context"

// These functions are automatically generated and maintained by Encore
// to simplify calling them from other services, as they were implemented as methods.
// They are automatically updated by Encore whenever your API endpoints change.

func Login(ctx context.Context) (*LoginResponse, error) {
	// The implementation is elided here, and generated at compile-time by Encore.
	return (*LoginResponse)(nil), nil
}

func Callback(ctx context.Context, p *CallbackRequest) (*CallbackResponse, error) {
	// The implementation is elided here, and generated at compile-time by Encore.
	return (*CallbackResponse)(nil), nil
}

func Logout(ctx context.Context) (*LogoutResponse, error) {
	// The implementation is elided here, and generated at compile-time by Encore.
	return (*LogoutResponse)(nil), nil
}
