// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package store

import (
	"context"
)

type Querier interface {
	InsertGreeting(ctx context.Context, name string) (int32, error)
}

var _ Querier = (*Queries)(nil)
