// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"context"

	"encore.dev/types/uuid"
)

type Querier interface {
	DeleteWebhook(ctx context.Context, db DBTX, id uuid.UUID) (*Webhook, error)
	GetWebhookByID(ctx context.Context, db DBTX, providerID string) (*Webhook, error)
	GetWebhookForBot(ctx context.Context, db DBTX, arg GetWebhookForBotParams) (*Webhook, error)
	InsertWebhook(ctx context.Context, db DBTX, arg InsertWebhookParams) (*Webhook, error)
}

var _ Querier = (*Queries)(nil)
