// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"database/sql"

	"encore.dev/types/uuid"
)

type Webhook struct {
	ID         uuid.UUID
	ProviderID string
	BotID      uuid.UUID
	Channel    string
	Name       string
	Token      string
	Deleted    sql.NullTime
}
