// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: avatar.sql

package db

import (
	"context"

	"encore.dev/types/uuid"
)

const getAvatar = `-- name: GetAvatar :one
SELECT bot_id, avatar FROM avatar WHERE bot_id = $1
`

func (q *Queries) GetAvatar(ctx context.Context, db DBTX, botID uuid.UUID) (*Avatar, error) {
	row := db.QueryRowContext(ctx, getAvatar, botID)
	var i Avatar
	err := row.Scan(&i.BotID, &i.Avatar)
	return &i, err
}

const insertAvatar = `-- name: InsertAvatar :exec
INSERT INTO avatar (bot_id, avatar) VALUES ($1, $2)
`

type InsertAvatarParams struct {
	BotID  uuid.UUID
	Avatar []byte
}

func (q *Queries) InsertAvatar(ctx context.Context, db DBTX, arg InsertAvatarParams) error {
	_, err := db.ExecContext(ctx, insertAvatar, arg.BotID, arg.Avatar)
	return err
}
