// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"database/sql"

	"encore.dev/types/uuid"
)

type Avatar struct {
	BotID  uuid.UUID
	Avatar []byte
}

type Bot struct {
	ID       uuid.UUID
	Name     string
	Prompt   string
	Profile  string
	Provider string
	Deleted  sql.NullTime
}
