/**
 * Placeholder API client for React Native.
 *
 * This file will be regenerated by Encore after running:
 *   task gen:api:native
 *
 * For now, this provides type stubs so the app compiles.
 */

export const Local = "http://localhost:4000";

// biome-ignore lint/suspicious/noExplicitAny: placeholder types
type Any = any;

export namespace auth {
	export type OAuthProvider = "GoogleOAuth" | "MicrosoftOAuth";

	export interface UserInfo {
		id: string;
		email: string;
		firstName: string | null;
		lastName: string | null;
		profilePictureUrl: string | null;
	}

	export interface SignInResponse {
		status: "complete" | "mfa_required" | "verify_email";
		accessToken?: string;
		refreshToken?: string;
		user?: UserInfo;
		pendingAuthenticationToken?: string;
		organizationName?: string;
	}

	export interface SignUpResponse {
		status: "complete" | "verify_email";
		accessToken?: string;
		refreshToken?: string;
		user?: UserInfo;
		userId?: string;
		pendingAuthenticationToken?: string;
		organizationName?: string;
	}

	export interface RefreshResponse {
		accessToken: string;
		refreshToken: string;
		user: UserInfo;
		organizationName?: string;
	}

	export interface SessionResponse {
		userID: string;
		email: string;
		role: "admin" | "member";
		organizationId: string;
	}

	export interface InvitationItem {
		id: string;
		email: string;
		status: string;
		createdAt: string;
		expiresAt: string;
	}
}

interface AuthOptions {
	auth?: () => Promise<{ authorization: string } | undefined>;
}

export default class Client {
	private baseUrl: string;
	private opts: AuthOptions;

	constructor(baseUrl: string, opts: AuthOptions = {}) {
		this.baseUrl = baseUrl.replace(/\/$/, "");
		this.opts = opts;
	}

	private async fetch(path: string, init?: RequestInit): Promise<Any> {
		const headers: Record<string, string> = {
			"Content-Type": "application/json",
			...(init?.headers as Record<string, string>),
		};
		const authResult = await this.opts.auth?.();
		if (authResult) {
			headers.Authorization = authResult.authorization;
		}
		const resp = await fetch(`${this.baseUrl}${path}`, {
			...init,
			headers,
		});
		if (!resp.ok) {
			const body = await resp.json().catch(() => ({}));
			throw new Error(body.message || `Request failed: ${resp.status}`);
		}
		const text = await resp.text();
		return text ? JSON.parse(text) : {};
	}

	auth = {
		signIn: (req: { email: string; password: string }): Promise<auth.SignInResponse> =>
			this.fetch("/api/auth/sign-in", { method: "POST", body: JSON.stringify(req) }),

		signUp: (req: { email: string; password: string; firstName: string; lastName: string }): Promise<auth.SignUpResponse> =>
			this.fetch("/api/auth/sign-up", { method: "POST", body: JSON.stringify(req) }),

		signOut: (req: { sessionId?: string }): Promise<{ success: true }> =>
			this.fetch("/api/auth/sign-out", { method: "POST", body: JSON.stringify(req) }),

		refresh: (req: { refreshToken: string }): Promise<auth.RefreshResponse> =>
			this.fetch("/api/auth/refresh", { method: "POST", body: JSON.stringify(req) }),

		getSession: (): Promise<auth.SessionResponse> =>
			this.fetch("/api/auth/session"),

		verifyEmail: (req: { code: string; pendingAuthenticationToken: string }): Promise<auth.RefreshResponse> =>
			this.fetch("/api/auth/verify-email", { method: "POST", body: JSON.stringify(req) }),

		forgotPassword: (req: { email: string; passwordResetUrl: string }): Promise<{ success: true }> =>
			this.fetch("/api/auth/forgot-password", { method: "POST", body: JSON.stringify(req) }),

		resetPassword: (req: { token: string; newPassword: string }): Promise<{ success: true }> =>
			this.fetch("/api/auth/reset-password", { method: "POST", body: JSON.stringify(req) }),

		getOAuthUrl: (req: { provider: auth.OAuthProvider; redirectUri: string }): Promise<{ url: string }> =>
			this.fetch(`/api/auth/oauth/url?provider=${req.provider}&redirectUri=${encodeURIComponent(req.redirectUri)}`),

		oauthCallback: (req: { code: string }): Promise<auth.RefreshResponse> =>
			this.fetch("/api/auth/oauth/callback", { method: "POST", body: JSON.stringify(req) }),

		sendInvitation: (req: { email: string; role: string }): Promise<{ invitationId: string; email: string; status: string }> =>
			this.fetch("/api/auth/invitations", { method: "POST", body: JSON.stringify(req) }),

		listInvitations: (): Promise<{ invitations: auth.InvitationItem[] }> =>
			this.fetch("/api/auth/invitations"),

		revokeInvitation: (req: { id: string }): Promise<void> =>
			this.fetch(`/api/auth/invitations/${req.id}`, { method: "DELETE" }),
	};
}
